slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: "mapping"
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "/scan"
    laser_min_range: 0.05
    laser_max_range: 12.0
    resolution: 0.05
    publish_period_sec: 1.0
